-- 회원 가입·로그인에 필요한 표 (specs/001 T007)
-- 팀 공통 ERD + 내 확장(docs/3-설계/ERD-변경-요청.md):
--   E-1 users.failed_login_count, users.locked_until (로그인 연속 실패 잠금)
--   E-2 탈퇴하지 않은 회원끼리 이메일·닉네임을 소문자로 비교해 중복 불가 (부분 인덱스)
--   E-3 category: 블로그 안에서 이름을 소문자로 비교해 중복 불가, color_index
--   E-6 blog.comments_read_at
-- 칸 정의는 Crowfoot 'myblog-제안' 문서(666)의 DDL과 같다. blog, category의 규칙은 specs/003이 정한다.

CREATE TABLE users (
    users_id           BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    email              VARCHAR(255) NOT NULL,
    password           VARCHAR(255) NOT NULL,
    nickname           VARCHAR(20)  NOT NULL,
    intro              VARCHAR(100),
    failed_login_count INTEGER      NOT NULL DEFAULT 0,
    locked_until       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL,
    deleted_at         TIMESTAMPTZ,
    CONSTRAINT users_pk PRIMARY KEY (users_id)
);

CREATE UNIQUE INDEX uq_users_email_active ON users (lower(email)) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_users_nickname_active ON users (lower(nickname)) WHERE deleted_at IS NULL;

CREATE TABLE blog (
    blog_id          BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    users_id         BIGINT       NOT NULL,
    name             VARCHAR(30)  NOT NULL,
    intro            VARCHAR(500),
    comments_read_at TIMESTAMPTZ,
    CONSTRAINT blog_pk PRIMARY KEY (blog_id),
    CONSTRAINT uk_blog_users_id UNIQUE (users_id),
    CONSTRAINT fk_blog_users FOREIGN KEY (users_id) REFERENCES users (users_id)
);

CREATE TABLE category (
    category_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    blog_id     BIGINT       NOT NULL,
    name        VARCHAR(20)  NOT NULL,
    intro       VARCHAR(255),
    visibility  VARCHAR(10)  NOT NULL DEFAULT 'public',
    is_default  BOOLEAN      NOT NULL,
    sort_order  INTEGER      NOT NULL,
    color_index SMALLINT     NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ,
    CONSTRAINT category_pk PRIMARY KEY (category_id),
    CONSTRAINT ck_category_visibility CHECK (visibility IN ('public', 'private')),
    CONSTRAINT fk_category_blog FOREIGN KEY (blog_id) REFERENCES blog (blog_id)
);

CREATE UNIQUE INDEX uq_category_blog_name ON category (blog_id, lower(name));
CREATE INDEX idx_category_blog_id ON category (blog_id);

COMMENT ON TABLE users IS '회원';
COMMENT ON TABLE blog IS '블로그';
COMMENT ON TABLE category IS '분류';
