-- 블로그·분류·글에 필요한 표 (specs/003 T003)
-- 팀 공통 ERD + 내 확장(docs/3-설계/ERD-변경-요청.md):
--   T-2 post.content에 기본값을 두지 않는다 (본문은 필수, 비어 있는지는 서버가 검사한다)
--   T-3 post.visibility는 'public', 'private'만 (ck_post_visibility)
--   E-4 post.request_key: 화면이 만든 1회용 요청 번호. 같은 번호로 글이 두 번 생기지 않게 한다 (003 D-6)
--   (인덱스) post (category_id, created_at, post_id): 이전·다음 글, 분류별 글 개수 (003 data-model 3, 가안)
-- 칸 정의는 Crowfoot 'myblog-제안' 문서(666)의 DDL과 같다.
-- post → category, post → topic 외래 키에는 연쇄 삭제가 없다: 글이 있는 분류는 DB가 지우지 못하게 막는다 (FR-040).

CREATE TABLE topic (
    topic_id   BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    topic_name VARCHAR(10) NOT NULL,
    sort_order INTEGER     NOT NULL,
    CONSTRAINT topic_pk PRIMARY KEY (topic_id),
    CONSTRAINT uk_topic_topic_name UNIQUE (topic_name)
);

CREATE TABLE post (
    post_id     BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_id BIGINT       NOT NULL,
    topic_id    BIGINT       NOT NULL,
    title       VARCHAR(100) NOT NULL,
    content     TEXT         NOT NULL,
    visibility  VARCHAR(10)  NOT NULL DEFAULT 'public',
    views       INTEGER      NOT NULL DEFAULT 0,
    request_key VARCHAR(36),
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ,
    CONSTRAINT post_pk PRIMARY KEY (post_id),
    CONSTRAINT uk_post_request_key UNIQUE (request_key),
    CONSTRAINT ck_post_visibility CHECK (visibility IN ('public', 'private')),
    CONSTRAINT fk_post_category FOREIGN KEY (category_id) REFERENCES category (category_id),
    CONSTRAINT fk_post_topic FOREIGN KEY (topic_id) REFERENCES topic (topic_id)
);

-- idx_post_category_id(666) 대신 작성 순서까지 담은 인덱스 하나를 둔다 (category_id로만 찾을 때도 쓰인다)
CREATE INDEX idx_post_category_created ON post (category_id, created_at, post_id);
CREATE INDEX idx_post_topic_id ON post (topic_id);

-- 주제는 서비스 전체에서 정해 둔 다섯 개다 (constitution 용어, 003 FR-046)
INSERT INTO topic (topic_name, sort_order) VALUES
    ('여행', 1),
    ('음식', 2),
    ('취미', 3),
    ('운동', 4),
    ('개발', 5);

COMMENT ON TABLE topic IS '주제';
COMMENT ON TABLE post IS '글';
