-- 댓글 (specs/005 T015, data-model 1). 칸은 팀 공통 ERD의 comment 그대로다.
--   D-7: 팀 ERD 옛 판의 UNIQUE(users_id, post_id)는 두지 않는다 (한 회원이 한 글에 댓글을 여러 개 쓸 수 있다. 팀 최신판에서도 지워짐).
--        parent_id(대댓글), is_secret(비밀 댓글)은 칸만 두고 이번에는 쓰지 않는다 (늘 NULL, false).
--   D-8: 팀 ERD의 comment_report는 이번에 쓰지 않아 만들지 않는다.
--   (인덱스, 가안) 글의 댓글을 오래된 순으로 읽기, 회원의 마지막 댓글 시각(5초 간격, D-2)
-- 외래 키에 연쇄 삭제는 없다 (003과 같음): 글을 지울 때 댓글 모듈이 PostDeletingEvent를 듣고 먼저 지운다.

CREATE TABLE comment (
    comment_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    users_id   BIGINT       NOT NULL,
    post_id    BIGINT       NOT NULL,
    parent_id  BIGINT,
    body       VARCHAR(500) NOT NULL,
    is_secret  BOOLEAN      NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ  NOT NULL,
    CONSTRAINT comment_pk PRIMARY KEY (comment_id),
    CONSTRAINT fk_comment_users FOREIGN KEY (users_id) REFERENCES users (users_id),
    CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES post (post_id),
    CONSTRAINT fk_comment_parent FOREIGN KEY (parent_id) REFERENCES comment (comment_id)
);

CREATE INDEX idx_comment_post_created ON comment (post_id, created_at, comment_id);
CREATE INDEX idx_comment_users_created ON comment (users_id, created_at);

COMMENT ON TABLE comment IS '댓글';
