-- 글 좋아요 (specs/005 T029, data-model 2). 칸은 팀 공통 ERD의 post_like 그대로다.
--   팀 ERD에 설명으로만 적혀 있던 "한 회원이 한 글에 한 번"을 실제 제약 UNIQUE(users_id, post_id)로 둔다 (FR-010, SC-002).
--   동시에 두 번 눌러도 줄은 하나다: 서버는 INSERT … ON CONFLICT DO NOTHING으로 넣는다 (research R-1, B-8).
-- 외래 키에 연쇄 삭제는 없다: 글 삭제(PostDeletingEvent)와 탈퇴(MemberWithdrawnEvent) 때 community 모듈이 먼저 지운다.

CREATE TABLE post_like (
    post_like_id BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    post_id      BIGINT      NOT NULL,
    users_id     BIGINT      NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    CONSTRAINT post_like_pk PRIMARY KEY (post_like_id),
    CONSTRAINT uk_post_like_users_post UNIQUE (users_id, post_id),
    CONSTRAINT fk_post_like_post FOREIGN KEY (post_id) REFERENCES post (post_id),
    CONSTRAINT fk_post_like_users FOREIGN KEY (users_id) REFERENCES users (users_id)
);

-- 글의 좋아요 수 세기, 글 삭제 때 지우기 (users_id로 찾는 것은 위 UNIQUE가 맡는다)
CREATE INDEX idx_post_like_post_id ON post_like (post_id);

COMMENT ON TABLE post_like IS '글 좋아요';
