-- 글 신고 (specs/005 T035, data-model 4). 칸은 팀 공통 ERD의 post_report다.
--   post_report_id는 자동 증가로 둔다 (팀 ERD에 설명이 빠져 있음, data-model 4).
--   T-3 (팀 ERD 변경 요청): reason은 'SPAM', 'ABUSE', 'ADULT', 'OTHER'만 (ck_post_report_reason).
--   E-7 (내 확장, 2026-10-08 결정): 한 회원이 한 글을 한 번만 신고한다 UNIQUE(users_id, post_id) (FR-019, SC-003).
--        동시에 두 번 보내도 하나만 들어가고 나머지는 ALREADY_REPORTED다 (INSERT … ON CONFLICT DO NOTHING).
--   처리 상태 칸은 두지 않는다: 이번에는 접수만 저장한다 (FR-020).
-- 외래 키에 연쇄 삭제는 없다: 글을 지울 때 community 모듈이 PostDeletingEvent로 먼저 지운다 (D-11).
-- 회원이 탈퇴해도 그 회원이 한 신고는 남는다 (002 D-5): 회원 줄도 남으므로 외래 키가 막지 않는다.

CREATE TABLE post_report (
    post_report_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    users_id       BIGINT       NOT NULL,
    post_id        BIGINT       NOT NULL,
    reason         VARCHAR(20)  NOT NULL,
    detail         VARCHAR(200),
    created_at     TIMESTAMPTZ  NOT NULL,
    CONSTRAINT post_report_pk PRIMARY KEY (post_report_id),
    CONSTRAINT uk_post_report_users_post UNIQUE (users_id, post_id),
    CONSTRAINT ck_post_report_reason CHECK (reason IN ('SPAM', 'ABUSE', 'ADULT', 'OTHER')),
    CONSTRAINT fk_post_report_users FOREIGN KEY (users_id) REFERENCES users (users_id),
    CONSTRAINT fk_post_report_post FOREIGN KEY (post_id) REFERENCES post (post_id)
);

CREATE INDEX idx_post_report_post_id ON post_report (post_id);

COMMENT ON TABLE post_report IS '글 신고';
