-- 블로그·글 일별 통계 (specs/006 T003, data-model 6, research R-3, D-6, D-7).
-- 팀 공통 ERD + 내 확장(docs/3-설계/ERD-변경-요청.md):
--   blog_daily_stat: 팀 ERD 칸 그대로. 설명으로만 적혀 있던 UNIQUE(blog_id, stat_date)를 두 칸에 실제 제약으로 둔다.
--                    views, visitors는 DEFAULT 0 ("없으면 만들고 있으면 +1"을 한 번에, R-3)
--   E-5 post_daily_stat: 글별 일별 조회수. 인기 글(최근 7일 조회수 순, D-6)에 쓴다
-- stat_date는 한국 날짜다 (서버가 계산해 넣는다, FR-036). 댓글 수 칸은 두지 않고 댓글 표에서 센다.
-- 외래 키에 연쇄 삭제는 없다 (003과 같음): 블로그를 닫을 때(BlogClosingEvent)와 글을 지울 때(PostDeletingEvent)
-- stats 모듈이 먼저 지운다 (StatsCleaner).

CREATE TABLE blog_daily_stat (
    blog_stat_id BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    blog_id      BIGINT  NOT NULL,
    stat_date    DATE    NOT NULL,
    views        INTEGER NOT NULL DEFAULT 0,
    visitors     INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT blog_daily_stat_pk PRIMARY KEY (blog_stat_id),
    CONSTRAINT uk_blog_daily_stat_blog_date UNIQUE (blog_id, stat_date),
    CONSTRAINT fk_blog_daily_stat_blog FOREIGN KEY (blog_id) REFERENCES blog (blog_id)
);

CREATE TABLE post_daily_stat (
    post_daily_stat_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    post_id      BIGINT  NOT NULL,
    stat_date    DATE    NOT NULL,
    views        INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT post_daily_stat_pk PRIMARY KEY (post_daily_stat_id),
    CONSTRAINT uk_post_daily_stat_post_date UNIQUE (post_id, stat_date),
    CONSTRAINT fk_post_daily_stat_post FOREIGN KEY (post_id) REFERENCES post (post_id)
);

-- 인기 글: 날짜 범위의 글별 합 (가안)
CREATE INDEX idx_post_daily_stat_date ON post_daily_stat (stat_date, post_id);

COMMENT ON TABLE blog_daily_stat IS '블로그 일별 통계';
COMMENT ON TABLE post_daily_stat IS '글 일별 조회수';
