-- 태그 (specs/005 T042, data-model 3). 칸은 팀 공통 ERD의 tag, post_tag 그대로다.
--   tag.name은 팀 ERD의 UNIQUE(name) 그대로 둔다. 서버가 소문자로 바꿔 저장하므로(D-10 A) 대소문자를 무시한 중복 불가가 된다.
--   post_tag의 기본키는 (post_id, tag_id): 한 글에 같은 태그가 두 번 붙지 않는다 (FR-014).
--   (인덱스) post_tag (tag_id): 태그로 글 찾기 (FR-015)
-- 외래 키에 연쇄 삭제는 없다: 글을 지울 때 글 모듈이 PostDeletingEvent로 연결을 먼저 지운다. tag 줄은 남긴다.

CREATE TABLE tag (
    tag_id BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name   VARCHAR(15) NOT NULL,
    CONSTRAINT tag_pk PRIMARY KEY (tag_id),
    CONSTRAINT uk_tag_name UNIQUE (name)
);

CREATE TABLE post_tag (
    post_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,
    CONSTRAINT post_tag_pk PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_post_tag_post FOREIGN KEY (post_id) REFERENCES post (post_id),
    CONSTRAINT fk_post_tag_tag FOREIGN KEY (tag_id) REFERENCES tag (tag_id)
);

CREATE INDEX idx_post_tag_tag_id ON post_tag (tag_id);

COMMENT ON TABLE tag IS '태그';
COMMENT ON TABLE post_tag IS '글-태그 연결';
