-- 글 이미지 기록 (specs/005 T052, data-model 5).
--   T-1 (팀 ERD 변경 요청, D-3): 이미지는 글을 저장하기 전에 먼저 올리므로 post_id는 비어 있을 수 있고(연결 전),
--        누가 올렸는지 users_id를 둔다 (연결 전 이미지는 올린 사람만 보고, 10장을 셀 때 쓴다).
--   storage_key는 저장소 안의 이름(posts/{UUID}.{확장자})이고 중복 불가다 (T003에서 팀에 함께 묻는 것).
--   (인덱스, 가안) 글의 이미지 찾기, 연결 전 이미지 찾기(정리 작업, 회원별 개수)
-- 외래 키에 연쇄 삭제는 없다: 글을 지울 때 image 모듈이 PostDeletingEvent로 기록을 먼저 지우고, 파일은 커밋 뒤에 지운다 (D-5).

CREATE TABLE post_image (
    post_image_id BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    post_id       BIGINT,
    users_id      BIGINT       NOT NULL,
    storage_key   VARCHAR(500) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT post_image_pk PRIMARY KEY (post_image_id),
    CONSTRAINT uk_post_image_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_post_image_post FOREIGN KEY (post_id) REFERENCES post (post_id),
    CONSTRAINT fk_post_image_users FOREIGN KEY (users_id) REFERENCES users (users_id)
);

CREATE INDEX idx_post_image_post_id ON post_image (post_id);
CREATE INDEX idx_post_image_unlinked ON post_image (users_id, created_at) WHERE post_id IS NULL;

COMMENT ON TABLE post_image IS '글 이미지';
